"""esquema inicial

Revision ID: c3b3688bf8aa
Revises: 
Create Date: 2026-08-07 12:04:37.785654

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3b3688bf8aa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('listas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('filtro_estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('libro', 'pelicula', 'serie', 'videojuego', 'podcast', name='mediatype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=60), nullable=True),
    sa.Column('external_source', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('cast', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('wishlist', 'pendiente', 'en_progreso', 'completado', 'abandonado', name='mediastatus'), nullable=False),
    sa.Column('priority', sa.Enum('alta', 'media', 'baja', name='priority'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('progress_current', sa.Float(), nullable=True),
    sa.Column('progress_total', sa.Float(), nullable=True),
    sa.Column('progress_unit', sa.String(length=30), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('hltb_hours', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('saga', sa.String(length=120), nullable=True),
    sa.Column('tmdb_collection_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('watched_at', sa.Date(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'season_number', 'episode_number', name='uq_episode_item_season_ep')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_item_id'), ['item_id'], unique=False)

    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'media_item_id')
    )
    op.create_table('media_item_tags',
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('media_item_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_item_tags')
    op.drop_table('list_items')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_item_id'))

    op.drop_table('episodes')
    op.drop_table('tags')
    op.drop_table('media_items')
    op.drop_table('listas')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
